tango_project/rango/urls.py
from django.conf.urls import url
from rango import views


app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    # Old, not used
    #url(r'^register/$', views.register, name='register'),
    #url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    #url(r'^logout/$', views.user_logout, name='logout')
    url(r'^search/$', views.search, name='search'),
    url(r'^goto/$', views.track_url, name='goto'),
    url('^add_profile', views.register_profile, name='register_profile'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    url(r'^profiles/$', views.list_profile, name='list_profiles')
]

tango_project/tango_project/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from rango import views
from registration.backends.simple.views import RegistrationView


class MyRegistrationView(RegistrationView):

    def get_success_url(self, user=None):
        return '/rango/add_profile'


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    likes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField(max_length=256)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.surname

tango_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Category, Page, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text='Please enter the category name')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        # An association between the ModelForm and model
        model = Category
        fields = ('name', )


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text='Please enter the title of the page')
    url = forms.URLField(max_length=256, help_text='Please enter the URL of the page')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # An association between the ModelForm and model
        model = Page
        fields = ('title', 'url', 'views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not(url.startswith('http://') or url.startswith('https://')):
            url = 'http://' + url
            cleaned_data['url'] = url
        return cleaned_data


class UserForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['password1'].label = 'Password'
        self.fields['password2'].label = 'Confirm password'

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")

        return self.cleaned_data


class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

tango_project/rango/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse, reverse, redirect
from rango.models import Category, Page, User, UserProfile
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
from rango.webhose_search import run_query


# A Helper method
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookies(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookies(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).days > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits


# A Helper method
def get_server_side_cookies(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def index(request):
    visitor_cookie_handler(request)
    context_dict = {'categories': Category.objects.order_by('-likes')[:5], 'pages': Page.objects.order_by('-views')[:5], 'visits': request.session['visits']}
    return render(request, 'rango/index.html', context_dict)


def about(request):
    context_dict = {'name': 'JMJAC'}
    return render(request, 'rango/about.html', context_dict)


def show_category(request, category_name_slug):
    context_dict = {'result_list': []}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['category'] = category
        context_dict['pages'] = pages
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    # Search functionality
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            context_dict['result_list'] = run_query(query)

    return render(request, 'rango/category.html', context_dict)


@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            # if the form is valid commit and direct user to index
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.save()
                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)
    return render(request, 'rango/add_page.html', {'form': form, 'category': category})


# Old, not used
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'rango/register.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


# Old, not used
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('rango:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            print(f'Invalid login details {username}, {password}')
            return render(request, 'rango/login.html', {'error': 'Invalid login details'})
    else:
        return render(request, 'rango/login.html', {})


@login_required
def restricted(request):
    return HttpResponse("Since you're logged in, you can see this text!")


# Old, not used
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def search(request):
    result_list = []
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)
    return render(request, 'rango/search.html', {'result_list': result_list})


def track_url(request):
    page_id = None
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
    if page_id:
        try:
            page = Page.objects.get(id=page_id)
            page.views += 1
            page.save()
            return redirect(page.url)
        except Exception as e:
            return HttpResponse(f'Page id {page_id} not found. Error code: {e}')
    print('No page id in get string')
    return redirect(reverse('index'))


@login_required
def register_profile(request):
    form = UserProfileForm
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profie = form.save(commit=False)
            user_profie.user = request.user
            user_profie.save()
            picture = form.picture

            return redirect(reverse('index'))
        else:
            print(form.errors)

    return render(request, 'registration/profile_registration.html', {'form': form})


def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect(reverse('index'))

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm({'website': userprofile.website, 'picture': userprofile.picture})

    if user.username == userprofile.user.username:
        if request.method == "POST":
            form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
            if form.is_valid():
                form.save(commit=True)
                return redirect(reverse('rango:profile', kwargs={'username': user.username}))
            else:
                print(form.errors)
    return render(request, 'rango/profile.html', {'userprofile': userprofile, 'selecteduser': user, 'form': form})


def list_profile(request):
    userprofile_list = UserProfile.objects.all()
    return render(request, 'rango/list_profiles.html', {'userprofile_list': userprofile_list})

tango_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
        <h2>Such a good way to say about yourself</h2>
        This was made by {{name}}. I heard he is a great guy!<br />
        <img src="{{MEDIA_URL}}cat.jpg" alt="Cat picture">
{% endblock %}

tango_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load bootstrap3 %}

{% block title_block %}
    Add New Category
{% endblock %}

{% block body_block %}
    <h1 class="form-signin-heading">Add Category</h1>
    <form role="form" id="category_form" method="POST" action="{% url 'rango:add_category' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-primary" type="submit" name="Submit">
                Create Category
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

tango_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load bootstrap3 %}

{% block title_block %}
    Add New Page
{% endblock %}

{% block body_block %}
{% if category %}
    <h1 class="form-signin-display">Add Page to {{category.name}}</h1>
    <form role="form" id="page_form" method="POST" action="{% url 'rango:add_page' category.slug %}">
        {% csrf_token %}
        {% bootstrap_form form layout='inline'%}
        {% buttons %}
        <button class="btn btn-primary" type="submit" name="submit">
            Add Page
        </button>
        {% endbuttons %}
    </form>
{% else %}
    <p>This category does not exist.</p>
{% endif %}
{% endblock %}

tango_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<!-- saved from url=(0053)https://v4-alpha.getbootstrap.com/examples/dashboard/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/mops.jpg' %}">

    <title>
        Rango -
        {% block title_block %}
            Tango with Django!
        {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css//dashboard.css' %}" rel="stylesheet">
  <style type="text/css"></style>
</head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item-active">
              <a class="nav-link" href="{% url 'rango:index' %}">Home</a>
            </li>
            <li class="nav-item">
             <a class="nav-link" href="{% url 'rango:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a>
            </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
            </li>
        {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">

            <ul class="nav nav-pills flex-column">
		        <li class="nav-item">Type to find a category</li>
	            <form>
			        <li class="nav-item"><input class="search-query form-control" type="text"
				        name="suggestion" value="" id="suggestion" />
			        </li>
		        </form>
	        </ul>
            <hr />
            <div id="cats">
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
            </div>
            <hr />


        </div>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main"><br />
         {% block body_block %}
         {% endblock %}
        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.1.1.slim.min.js.download' %}" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/tether.min.js.download' %}" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js.download' %}"></script>
 </body>
</html>

tango_project/templates/rango/base_old.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Rango -
        {% block title_block %}
            Tango with Django!
        {% endblock %}
    </title>
</head>
<body>
    <div>
    {% block body_block %}
    {% endblock %}
    </div>
    <hr />
    <div>
        <ul>
            <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'auth_password_change' %}">Change password</a> </li>
                <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a> </li>
            {% else %}
                <li><a href="{% url 'auth_login' %}">Sing in</a> </li>
                <li><a href="{% url 'registration_register' %}">Sing Up</a></li>
            {% endif %}
        </ul>
    </div>
    <hr />
    <div>
        {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
    </div>
</body>
</html>

tango_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{category.name}}
{% endblock %}

{% block body_block %}
<div>
    {% if category %}
        <h1>{{category.name}}</h1>
        {% if pages %}
            <ul>
             {% for page in pages %}
                <li><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{page.title}}</a><span class="tag tag-pill tag-primary">
                    {% if page.views > 1 %}
                        {{page.views}} views</span></li>
                    {% else %}
                        {{page.views}} view</span></li>
                    {% endif %}
             {% endfor %}
            </ul>
        {% else %}
            <strong>No pages in this category.</strong>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add a New Page</a><br />
        {% endif %}
    {% else %}
        The specified category does not exist!
    {% endif %}
    {% if user.is_authenticated %}
    <div>
    <br />
    <h1>Search!</h1>
    <br />
    <form class="form-inline" id="user_form" method="POST" action="{% url 'rango:show_category' category.slug %}">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" size="50" name="query" value="" id="query" />
        </div>
        <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
    </form>

    <div>
        {% if result_list %}
        <h3>Results</h3>
        <div class="list-group">
            {% for result in result_list %}
                <div class="list-group-item">
                    <h4 class="list-group-item-heading"><a href="{{ result.link }}">{{result.title}}</a></h4>
                    <p class="list-group-item-text">{{result.summary}}</p>
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    </div>
    {% endif %}
</div>
{% endblock %}

tango_project/templates/rango/cats.html
<ul>
{% if cats %}
    {% for c in cats %}
        {% if c == act_cat %}
            <li> <strong> <a href="{% url 'rango:show_category' c.slug %}">{{c.name}}</a> </strong> </li>
        {% else %}
            <li> <a href="{% url 'rango:show_category' c.slug %}">{{c.name}}</a> </li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}
</ul>

tango_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Home
{% endblock %}

{% block body_block %}
<div class="jumbotron">
    {% if user.is_authenticated %}
        <h1 class="display-3">Hi {{user.username}}!</h1>
    {% else %}
        <h1 class="display-3">Hi there!</h1>
    {% endif %}
        <h3>You've visited us {{visits}} times</h3>
</div>
<div class="row marketing">
        <div class="col-lg-6">
        {% if categories %}
            <h1>Most Liked Categories</h1>
            <ul class="list-group">
            {% for category in categories %}
                <li class="list-group"><a href="{% url 'rango:show_category' category.slug %}">{{category.name}}</a> </li>
            {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories</strong>
        {% endif %}
        </div>
        <div class="col-lg'6">
        {% if pages %}
            <h1>Most Viewed Pages</h1>
            <ul class="list-group">
            {% for page in pages %}
                <li class="list-group"><a href="{{page.url}}">{{page.title}}</a> </li>
                {% endfor %}
            </ul>
        {% else %}
                <strong>There are no pages</strong>
        {% endif %}
        </div>
</div>
<img src= "{% static 'images/mops.jpg' %}" alt="Mops"s>
{% endblock %}

tango_project/templates/rango/list_profiles.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    User Profiles
{% endblock %}

{% block body_block %}
<div class="panel">
    {% if userprofile_list %}
    <div class="panel-heading">
        <div class="panel-body">
            <div class="list-group">
                {% for listuser in userprofile_list %}
                    <div class="list-group-item">
                        {% if listuser.picture %}
                            <img src="{{MEDIA_URL}}{{listuser.picture}}" width="64" height="64" alt="{{listuser.user.username}}">
                        {% else %}
                            <img width="64" height="64" src="http://lorempixel.com/64/64/"/>
                        {% endif %}
                        <h4 class="list-group-item"><a href="{% url 'rango:profile' listuser.user.username %}">{{listuser.user.username}}</a></h4>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% else %}
        <p>There are no users for the site.</p>
    {% endif %}
</div>
{% endblock %}

tango_project/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to rango</h1>
    <form id="login_form" method="POST" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50"/>
        <br />
        Password: <input type="password" name="password" value="" size="50"/>
        <br />
        {% if error %}
            {{error}}<br />
        {% endif %}
        <input type="submit" value="submit" />
    </form>
{% endblock %}

tango_project/templates/rango/profile.html
{% extends 'rango/base.html' %}

{% block title_block %}
    {{selecteduser.username}} - Profile
{% endblock %}

{% block body_block %}
    <h1>{{selecteduser.username}} Profile</h1>
    <img src="{{ MEDIA_URL }}{{userprofile.picture}}"
         width="300"
         height="300"
         alt="{{selecteduser.username}}"/>
    <p><strong>Website:</strong><a href="{{userprofile.website}}"> {{userprofile.website}}</a></p>
    <br />
    <div>
        {% if selecteduser.username == user.username %}
        <hr />
        <h2>Edit:</h2>
            <form method="POST" action="." enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary" type="submit" value="Update">Update</button>
            </form>
        {% endif %}
    </div>
<div id="edit_profile"></div>
{% endblock %}

tango_project/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to homepage.</a>
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="POST" action="{% url 'rango:register' %}"
              enctype="multipart/form-data">
            {% csrf_token %}

            {{user_form.as_p}}
            {{profile_form.as_p}}

            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

tango_project/templates/rango/search.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    Search
{% endblock %}

{% block body_block %}
<div>
    <h1>Search with Rango</h1>
    <br />
    <form class="form-inline" id="user_form" method="POST" action="{% url 'rango:search' %}">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" size="50" name="query" value="" id="query" />
        </div>
        <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
    </form>

    <div>
        {% if result_list %}
        <h3>Results</h3>
        <div class="list-group">
            {% for result in result_list %}
                <div class="list-group-item">
                    <h4 class="list-group-item-heading"><a href="{{ result.link }}">{{result.title}}</a></h4>
                    <p class="list-group-item-text">{{result.summary}}</p>
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}